// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mappings.sql

package database

import (
	"context"
)

const getMapping = `-- name: GetMapping :one
SELECT path, url FROM mappings
WHERE path = $1
`

func (q *Queries) GetMapping(ctx context.Context, path string) (Mapping, error) {
	row := q.db.QueryRowContext(ctx, getMapping, path)
	var i Mapping
	err := row.Scan(&i.Path, &i.Url)
	return i, err
}
